"""ZK Proof-of-Gradient System — architecture.md compliant.

Architecture (architecture.md):
  - CHUNK_SIZE = 2048 (matches Rust constant)
  - Quantization scale = 10^6 (FP32 → finite field integer)
  - Padding: zero-pad gradient until len % 2048 == 0
  - EMA-based dynamic bound: B_l = EMA(Q25 * (1 + γ), β=0.9, γ=5.0)
  - Defense pipeline: Merkle → IO check → Cosine filter → Multi-Krum → IVC fold

# Circuit state z = [model_fp, ref_grad_fp, grad_fp_accum, norm_sq_accum, directional_fp_accum, ref_fp_accum, step_count] (7 elements)
The circuit accumulates both the Schwartz-Zippel fingerprint AND the quantized L2 norm².
"""

import logging
import re
import time
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import numpy as np
import torch

logger = logging.getLogger(__name__)

# ── Rust bridge ────────────────────────────────────────────────────────────────
_ZKP_AVAILABLE = False
_GradientZKProver = None

try:
    from fl_zkp_bridge import GradientZKProver as _GradientZKProver
    _ZKP_AVAILABLE = True
    logger.info(
        "✓ fl_zkp_bridge loaded — GradientFingerprintCircuit (CHUNK=2048, 7-state) enabled"
    )
except ImportError:
    _GradientZKProver = None
    _ZKP_AVAILABLE = False
    logger.warning(
        "fl_zkp_bridge not installed. Real ZKP is unavailable; build with: "
        "cd sonobe/fl-zkp-bridge && maturin develop --release"
    )

# ── Constants (architecture.md §1) ────────────────────────────────────────────
CHUNK_SIZE = 2048          # Must match Rust CHUNK_SIZE constant
SCALE      = 1_000_000     # 10^6 quantization: FP32 → finite field integer
EMA_BETA   = 0.9           # Sybil EMA momentum (architecture.md §3.1)
EMA_GAMMA  = 5.0           # Tolerance multiplier
QUANT_SAFE = 2 ** 63 - 1   # Keep fingerprints in i64 range

# Batch wire format from `fl_zkp_bridge::encode_proof_batches` (magic PGFB)
BATCH_MAGIC = b"PGFB"


# ── GradientProofBundle ────────────────────────────────────────────────────────

@dataclass
class GradientProofBundle:
    """A ZK proof bundle: fingerprint commitment + L2 norm² commitment.

    Generated by ModelAgnosticProver.generate_proof().
    Verified by verify_gradient_proof() via PG::verify (real, no re-proving).
    """
    proof_bytes: bytes         # Self-contained IVC proof + VP bytes
    model_fp: int              # Committed model fingerprint (z_0[0])
    grad_fp: int               # Final accumulated fingerprint z_i[2] (for logging)
    norm_sq_quantized: float   # Final accumulated norm² z_i[3] (quantized field units)
    directional_fp_quantized: float # Final accumulated dir_fp z_i[4] (quantized field units)
    num_steps: int             # Number of IVC steps (= num chunks proved)
    num_gradient_elements: int
    client_id: int
    round_number: int
    prove_time_ms: float
    is_real: bool              # True = ProtoGalaxy IVC
    model_type: str = "unknown"

    @property
    def proof_size(self) -> int:
        return len(self.proof_bytes)


@dataclass
class ZKProof:
    """Pipeline-facing proof object: wraps IVC bundle bytes plus FL metadata.

    `gradient_bundle` holds the same proof as `proof_bytes` for single-client proofs.
    Galaxy batch proofs use `proof_bytes` with BATCH_MAGIC and embed a nested
    `GradientProofBundle` placeholder for bookkeeping.
    """

    proof_bytes: bytes
    claimed_sum: float
    num_steps: int
    client_id: int
    round_number: int
    prove_time_ms: float
    is_real: bool
    layer_sums: List[float] = field(default_factory=list)
    gradient_bundle: Optional[GradientProofBundle] = None

    @property
    def proof_size(self) -> int:
        return len(self.proof_bytes)

    @classmethod
    def from_gradient_bundle(
        cls,
        gb: GradientProofBundle,
        layer_sums: List[float],
    ) -> "ZKProof":
        return cls(
            proof_bytes=gb.proof_bytes,
            claimed_sum=float(sum(layer_sums)),
            num_steps=gb.num_steps,
            client_id=gb.client_id,
            round_number=gb.round_number,
            prove_time_ms=gb.prove_time_ms,
            is_real=gb.is_real,
            layer_sums=list(layer_sums),
            gradient_bundle=gb,
        )


# ── EMA Bound Manager (architecture.md §3.1) ───────────────────────────────────

class EMABoundManager:
    """Dynamic L2 norm bound using Exponential Moving Average.

    B_l^(t+1) = β * B_l^(t) + (1-β) * Q25(client_norms) * (1 + γ)

    Sybil resilience: attackers controlling <75% of clients cannot inflate Q25.
    """

    def __init__(
        self,
        beta: float = EMA_BETA,
        gamma: float = EMA_GAMMA,
        init_bound: Optional[float] = None,
    ):
        self.beta = beta
        self.gamma = gamma
        self._bound: Optional[float] = init_bound  # None = cold start

    @property
    def bound(self) -> Optional[float]:
        return self._bound

    def update(self, client_norms: List[float]) -> float:
        """Update EMA with new round's client norms. Returns new bound."""
        if not client_norms:
            return self._bound or 1.0

        q25 = float(np.percentile(client_norms, 25))
        current_target = q25 * (1.0 + self.gamma)

        if self._bound is None:
            # Cold start (round 0): initialize from warm-up data
            self._bound = current_target
        else:
            self._bound = self.beta * self._bound + (1.0 - self.beta) * current_target

        logger.debug(
            f"EMA bound update: Q25={q25:.4f}, target={current_target:.4f}, bound={self._bound:.4f}"
        )
        return self._bound

    def check(self, norm: float) -> bool:
        """Return True if norm is within bound."""
        if self._bound is None:
            return True  # Cold start: accept all
        return norm <= self._bound


# ── FingerprintHelper ──────────────────────────────────────────────────────────

class FingerprintHelper:
    """Schwartz-Zippel fingerprint utilities for model binding and gradient commitment."""

    @staticmethod
    def quantize(arr: np.ndarray) -> np.ndarray:
        """Apply 10^6 quantization to map FP32 gradients to integer field elements.
        (architecture.md §1 — Quantization Scale Factor: 10^6)
        """
        return (arr * SCALE).astype(np.int64)

    @staticmethod
    def generate_random_chunks(
        num_elements: int,
        round_number: int,
        client_id: int = 0,
        chunk_size: int = CHUNK_SIZE,
    ) -> List[np.ndarray]:
        """Deterministic Fiat-Shamir random challenges (same seed → same r).

        Both client and server independently derive identical r_chunks from
        (round_number, client_id) — preventing cross-client proof replay.
        """
        rng = np.random.RandomState(seed=round_number * 100_003 + client_id * 7 + 17)
        num_chunks = (num_elements + chunk_size - 1) // chunk_size
        return [rng.randn(chunk_size) for _ in range(num_chunks)]

    @staticmethod
    def compute_model_fingerprint(
        params: List[torch.Tensor],
        round_number: int,
        sample_size: int = 500,
    ) -> Tuple[int, np.ndarray]:
        """Schwartz-Zippel model fingerprint: <r, W_sampled>."""
        flat = torch.cat([p.detach().cpu().flatten() for p in params]).numpy()
        total = len(flat)
        rng = np.random.RandomState(seed=round_number * 999_983 + 31)
        indices = rng.choice(total, size=min(sample_size, total), replace=False)
        sampled = flat[indices]
        r_seed = np.random.RandomState(seed=round_number * 777_777 + 13)
        r_sampled = r_seed.randn(len(indices))
        fp = int(np.sum(
            (r_sampled * SCALE).astype(np.int64) * FingerprintHelper.quantize(sampled)
        ))
        return fp % QUANT_SAFE, sampled

    @staticmethod
    def compute_gradient_fingerprint(
        grad_flat_quantized: np.ndarray,
        r_chunks: List[np.ndarray],
        chunk_size: int = CHUNK_SIZE,
        apply_modulo: bool = True,
    ) -> int:
        """Compute expected fingerprint from pre-quantized gradient and Fiat-Shamir chunks."""
        fp_accum = 0
        for i, r_chunk in enumerate(r_chunks):
            start = i * chunk_size
            end = start + chunk_size
            g_slice = grad_flat_quantized[start:end]
            if len(g_slice) < chunk_size:
                g_slice = np.pad(g_slice, (0, chunk_size - len(g_slice)))
            dot = int(np.sum((r_chunk * SCALE).astype(np.int64) * g_slice))
            fp_accum += dot
        return fp_accum % QUANT_SAFE if apply_modulo else fp_accum


# ── Cosine Similarity Filter (architecture.md §3.2) ───────────────────────────

def cosine_similarity_filter(
    updates: List[dict],
    threshold: float = 0.5,
) -> List[dict]:
    """Layer 2 statistical filter: remove updates with cosine similarity < threshold.

    Compares each client's gradient to the mean of all others.
    Clips the update list before cosine computation to avoid Byzantine poisoning
    of the reference vector — uses only the bottom-50% by norm as reference.
    (architecture.md §3.2 — Statistical Filtering: Cosine → Multi-Krum)
    """
    if len(updates) < 2:
        return updates

    # Flatten all gradients
    flattened = []
    for u in updates:
        grads = u.get("gradients", u.get("gradients_list", []))
        flat = np.concatenate([
            g.detach().cpu().numpy().flatten() if isinstance(g, torch.Tensor)
            else np.array(g).flatten()
            for g in grads
        ])
        flattened.append(flat)

    stacked = np.array(flattened)   # (n, d)
    norms = np.linalg.norm(stacked, axis=1)

    # Use the lower-50% norm clients as the reference to resist Byzantine inflation
    n = len(updates)
    bottom_50 = np.argsort(norms)[:max(1, n // 2)]
    reference = np.mean(stacked[bottom_50], axis=0)
    ref_norm = np.linalg.norm(reference)

    accepted = []
    for i, (flat, u) in enumerate(zip(stacked, updates)):
        if ref_norm < 1e-10 or norms[i] < 1e-10:
            accepted.append(u)
            continue
        cos_sim = float(np.dot(flat, reference) / (norms[i] * ref_norm))
        if cos_sim >= threshold:
            accepted.append(u)
        else:
            cid = u.get("client_id", i)
            logger.info(f"  [Cosine] Client {cid}: REJECTED — cos_sim={cos_sim:.3f} < {threshold:.2f}")

    return accepted


# ── ModelAgnosticProver (architecture.md §4 Phase 1) ──────────────────────────

class ModelAgnosticProver:
    """Generates ZK proof bundles via ProtoGalaxy IVC.

    Protocol:
      1. Flatten + quantize gradients (×10^6)
      2. Zero-pad to multiple of CHUNK_SIZE=2048
      3. For each chunk: prove_chunk(g_chunk, r_chunk) → IVC fold step
      4. generate_proof_bundle() → self-contained bytes (IVC proof + VP)
    """

    def __init__(self, grad_sample_size: int = 4096):
        """
        Args:
            grad_sample_size: Elements to prove. With CHUNK_SIZE=2048:
                4096 → 2 IVC steps (fast, ~6 digits security margin).
                Use full gradient for small models (linear ~7850 → 4 steps).
        """
        if not (_ZKP_AVAILABLE and _GradientZKProver is not None):
            raise RuntimeError(
                "ProtoGalaxy ZKP bridge is unavailable. "
                "Build sonobe/fl-zkp-bridge (maturin develop --release)."
            )
        self._is_real = True
        self.grad_sample_size = grad_sample_size

    @property
    def is_real(self) -> bool:
        return self._is_real

    def _sample_and_quantize(
        self,
        grad_flat: np.ndarray,
        round_number: int,
        client_id: int,
    ) -> Tuple[np.ndarray, np.ndarray]:
        """Sample, quantize (×10^6), and return (g_quantized, indices)."""
        total = len(grad_flat)
        n = min(self.grad_sample_size, total)
        rng = np.random.RandomState(seed=round_number * 888_881 + client_id * 11 + 3)
        indices = np.sort(rng.choice(total, size=n, replace=False))
        sampled = grad_flat[indices]
        quantized = FingerprintHelper.quantize(sampled).astype(np.int64)  # strict i64 for Rust
        return quantized, indices

    def generate_proof(
        self,
        gradients: List[torch.Tensor],
        ref_gradients: List[torch.Tensor],
        model_fp: int,
        ref_grad_fp: int,
        client_id: int,
        round_number: int,
    ) -> GradientProofBundle:
        """Generate ZK proof bundle (architecture.md §4 Phase 1 Step 4).

        Args:
            gradients: All local gradient tensors
            ref_gradients: Global reference gradient tensors for directional check
            model_fp:  Committed model fingerprint
            ref_grad_fp: Committed reference gradient fingerprint
            client_id: Client ID (for Fiat-Shamir domain separation)
            round_number: FL round

        Returns:
            GradientProofBundle — send to server for PG::verify
        """
        start = time.time()

        # Flatten all layers
        grad_flat = np.concatenate([
            g.detach().cpu().numpy().flatten() for g in gradients
        ])
        ref_flat = np.concatenate([
            g.detach().cpu().numpy().flatten() for g in ref_gradients
        ])

        # Sample + quantize (10^6 scale, architecture.md §1)
        g_quantized, indices = self._sample_and_quantize(grad_flat, round_number, client_id)
        r_quantized = FingerprintHelper.quantize(ref_flat[indices]).astype(np.float64)
        n_sampled = len(g_quantized)

        # Zero-pad to multiple of CHUNK_SIZE (architecture.md §1)
        pad_len = (CHUNK_SIZE - (n_sampled % CHUNK_SIZE)) % CHUNK_SIZE
        g_padded = np.pad(g_quantized, (0, pad_len))
        ref_padded = np.pad(r_quantized, (0, pad_len))
        num_chunks = len(g_padded) // CHUNK_SIZE

        # Fiat-Shamir challenges (deterministic, architecture.md §4 Phase 1)
        r_chunks = FingerprintHelper.generate_random_chunks(
            n_sampled, round_number, client_id, CHUNK_SIZE
        )
        while len(r_chunks) < num_chunks:
            r_chunks.append(np.zeros(CHUNK_SIZE))

        # Calculate the precise mathematical reference accumulator to pass to the strict rust bindings
        true_ref_fp = FingerprintHelper.compute_gradient_fingerprint(ref_padded.astype(np.int64), r_chunks, apply_modulo=False)

        bundle_bytes, num_steps, grad_fp, norm_sq_q, dir_fp_q = self._prove_real(
            model_fp, true_ref_fp, g_padded, ref_padded, r_chunks, num_chunks
        )

        elapsed_ms = (time.time() - start) * 1000
        return GradientProofBundle(
            proof_bytes=bundle_bytes,
            model_fp=model_fp,
            grad_fp=grad_fp,
            norm_sq_quantized=norm_sq_q,
            directional_fp_quantized=dir_fp_q,
            num_steps=num_steps,
            num_gradient_elements=len(grad_flat),
            client_id=client_id,
            round_number=round_number,
            prove_time_ms=elapsed_ms,
            is_real=self._is_real,
        )

    def _prove_real(
        self,
        model_fp: int,
        ref_grad_fp: int,
        g_padded: np.ndarray,
        ref_padded: np.ndarray,
        r_chunks: List[np.ndarray],
        num_chunks: int,
    ) -> Tuple[bytes, int, int, float, float]:
        """Real ProtoGalaxy IVC proof (CHUNK_SIZE=2048, 6-element state)."""
        prover = _GradientZKProver()
        prover.initialize(model_fp, ref_grad_fp)

        # Ensure strict int64 bounds for the Rust bridge scaling
        g_int = g_padded.astype(np.int64)
        ref_int = ref_padded.astype(np.int64)

        for i in range(num_chunks):
            g_chunk = g_int[i * CHUNK_SIZE:(i + 1) * CHUNK_SIZE].tolist()
            # Random variables must also rigorously bind to the same scaler magnitude 
            r_chunk = (r_chunks[i] * SCALE).astype(np.int64).tolist()
            ref_chunk = ref_int[i * CHUNK_SIZE:(i + 1) * CHUNK_SIZE].tolist()
            prover.prove_chunk(g_chunk, r_chunk, ref_chunk)

        bundle = bytes(prover.generate_proof_bundle())
        num_steps = prover.get_num_steps()

        # Compute Python-side fingerprint for cross-check logging
        grad_fp = FingerprintHelper.compute_gradient_fingerprint(g_padded.astype(np.int64), r_chunks)

        # Approximate from Python (exact value is in IVC public output)
        norm_sq_q = float(np.sum(g_padded.astype(np.int64) ** 2))
        dir_fp_q = float(np.sum(g_padded.astype(np.int64) * ref_padded.astype(np.int64)))

        logger.info(
            f"✓ IVC proof: {len(bundle)//1024}KB, {num_steps} steps, "
            f"model_fp={model_fp}, norm_sq≈{norm_sq_q:.2e}, dir_fp≈{dir_fp_q:.2e}"
        )
        return bundle, num_steps, grad_fp, norm_sq_q, dir_fp_q


class GradientSumCheckProver:
    """Back-compat name: proves per-client gradients via ProtoGalaxy IVC (ModelAgnosticProver)."""

    def __init__(
        self,
        global_model: Optional[torch.nn.Module] = None,
        grad_sample_size: int = 4096,
    ):
        self.global_model = global_model
        self.grad_sample_size = grad_sample_size
        self._inner: Optional[ModelAgnosticProver] = None
        if _ZKP_AVAILABLE:
            self._inner = ModelAgnosticProver(grad_sample_size=grad_sample_size)

    @property
    def _is_real(self) -> bool:
        return bool(_ZKP_AVAILABLE and self._inner is not None)

    def prove_gradient_sum(
        self,
        gradients: List[torch.Tensor],
        client_id: int,
        round_number: int,
        model_fp: Optional[int] = None,
        ref_gradients: Optional[List[torch.Tensor]] = None,
    ) -> ZKProof:
        """Generate one client's IVC proof over gradient samples.

        When ``global_model`` was passed to the constructor, fingerprints bind to the
        current global weights; otherwise uses all-zero reference (test mode).
        """
        if self._inner is None:
            raise RuntimeError("fl_zkp_bridge is not available")

        if ref_gradients is None:
            if self.global_model is not None:
                ref_gradients = [
                    torch.zeros_like(p, device=p.device) for p in self.global_model.parameters()
                ]
            else:
                ref_gradients = [torch.zeros_like(g) for g in gradients]

        if model_fp is None:
            if self.global_model is None:
                model_fp = 0
            else:
                model_fp, _ = FingerprintHelper.compute_model_fingerprint(
                    list(self.global_model.parameters()), round_number
                )

        gb = self._inner.generate_proof(
            gradients=gradients,
            ref_gradients=ref_gradients,
            model_fp=model_fp,
            ref_grad_fp=0,
            client_id=client_id,
            round_number=round_number,
        )
        layer_sums = [float(g.detach().float().sum().item()) for g in gradients]
        return ZKProof.from_gradient_bundle(gb, layer_sums)

    @staticmethod
    def verify_proof(proof: ZKProof) -> bool:
        if not proof.proof_bytes:
            return False
        if proof.proof_bytes[: len(BATCH_MAGIC)] == BATCH_MAGIC:
            if not _ZKP_AVAILABLE or _GradientZKProver is None:
                return False
            ok, _msg = _GradientZKProver.verify_batch_bundle_static(list(proof.proof_bytes))
            return bool(ok)
        if proof.gradient_bundle is not None:
            ok, _ = verify_gradient_proof(
                proof.gradient_bundle,
                expected_model_fp=None,
                ema_bound=None,
            )
            return bool(ok)
        return False


class GalaxyProofFolder:
    """Packages multiple client IVC proofs into one verified batch blob (O(N) verify)."""

    def fold_galaxy_proofs(self, proofs: List[ZKProof], galaxy_id: int) -> ZKProof:
        if not proofs:
            return ZKProof(
                proof_bytes=b"",
                claimed_sum=0.0,
                num_steps=0,
                client_id=-1,
                round_number=0,
                prove_time_ms=0.0,
                is_real=False,
                layer_sums=[],
            )
        subs = [p.gradient_bundle for p in proofs if p.gradient_bundle is not None]
        if len(subs) != len(proofs):
            raise RuntimeError("Galaxy fold requires each ZKProof.gradient_bundle to be set")
        folded_gb = fold_gradient_proof_bundles(subs)
        all_layers: List[float] = []
        for p in proofs:
            all_layers.extend(p.layer_sums)
        return ZKProof(
            proof_bytes=folded_gb.proof_bytes,
            claimed_sum=float(sum(p.claimed_sum for p in proofs)),
            num_steps=sum(p.num_steps for p in proofs),
            client_id=galaxy_id,
            round_number=proofs[0].round_number,
            prove_time_ms=0.0,
            is_real=all(p.is_real for p in proofs),
            layer_sums=all_layers,
            gradient_bundle=folded_gb,
        )


def fold_gradient_proof_bundles(bundles: List[GradientProofBundle]) -> GradientProofBundle:
    """Pack independent client bundles after full per-bundle PG::verify in Rust."""
    if not bundles:
        raise ValueError("fold_gradient_proof_bundles: empty bundle list")
    if not _ZKP_AVAILABLE or _GradientZKProver is None:
        raise RuntimeError("fl_zkp_bridge is required for proof batching")
    raw = [list(b.proof_bytes) for b in bundles]
    folded = _GradientZKProver.fold_proofs_bundle(raw)
    return GradientProofBundle(
        proof_bytes=bytes(folded),
        model_fp=bundles[0].model_fp,
        grad_fp=0,
        norm_sq_quantized=0.0,
        directional_fp_quantized=0.0,
        num_steps=sum(b.num_steps for b in bundles),
        num_gradient_elements=sum(b.num_gradient_elements for b in bundles),
        client_id=0,
        round_number=bundles[0].round_number,
        prove_time_ms=0.0,
        is_real=True,
    )


# ── verify_gradient_proof (architecture.md §4 Phase 2) ─────────────────────────

def verify_gradient_proof(
    bundle: GradientProofBundle,
    expected_model_fp: Optional[int] = None,
    ema_bound: Optional["EMABoundManager"] = None,
) -> Tuple[bool, str]:
    """Verify a ZK proof bundle.

    1. Calls PG::verify (real cryptographic check, NOT re-proving)
    2. Extract z_i output state from the proof mathematically.
    3. Checks norm_sq <= EMA bound²
    4. Checks directional_fp >= 0 (strictly blocks obtuse angles / sign-flips)

    Returns (True, "Valid") if ALL checks pass.
    architecture.md §4 Phase 4: O(1) IVC verification.
    """
    if expected_model_fp is not None and bundle.model_fp != expected_model_fp:
        return False, f"model_fp mismatch (expected {expected_model_fp}, got {bundle.model_fp})"

    if not bundle.proof_bytes:
        logger.warning(f"Client {bundle.client_id}: empty proof bundle")
        return False, "empty proof bundle"

    # Batch envelope: N independent IVC bundles (each already cryptographically verified in Rust).
    if bundle.proof_bytes[: len(BATCH_MAGIC)] == BATCH_MAGIC:
        if not _ZKP_AVAILABLE or _GradientZKProver is None:
            return False, "fl_zkp_bridge unavailable for batch verification"
        ok, msg = _GradientZKProver.verify_batch_bundle_static(list(bundle.proof_bytes))
        if not ok:
            return False, msg
        return True, msg or "Valid batch"

    norm_sq_quantized = bundle.norm_sq_quantized
    dir_fp_quantized = bundle.directional_fp_quantized

    if bundle.is_real:
        # Real ProtoGalaxy IVC verification
        try:
            # Returns (is_valid, norm_sq_str, dir_fp_str, error_msg) mathematical outputs directly from proof state!
            ok, norm_str, dir_str, msg = _GradientZKProver.verify_proof_bundle_static(list(bundle.proof_bytes))
            if not ok:
                logger.warning(f"Client {bundle.client_id}: PG::verify FAILED ({msg})")
                return False, f"PG::verify FAILED: {msg}"

            m_norm = re.search(r'BigInt\(\[([^\]]+)\]\)', norm_str)
            if m_norm:
                parts = [int(x.strip()) for x in m_norm.group(1).split(',')]
                val = 0
                for i, p in enumerate(parts):
                    val += p * (2**(64*i))
                norm_sq_quantized = float(val)

            m_dir = re.search(r'BigInt\(\[([^\]]+)\]\)', dir_str)
            if m_dir:
                parts = [int(x.strip()) for x in m_dir.group(1).split(',')]
                val = 0
                for i, p in enumerate(parts):
                    val += p * (2**(64*i))
                # Negative fields in Fr map to large positive ints (p - val). 
                # For quantization limits, any value > p/2 is negative in logic.
                # Assuming BN254 p is ~2^254
                p_half = 2**253
                if val > p_half:
                    dir_fp_quantized = -float(2**254 - val)
                else:
                    dir_fp_quantized = float(val)

            logger.debug(f"Client {bundle.client_id}: PG::verify PASS (norm: {norm_sq_quantized}, dir: {dir_fp_quantized})")
        except Exception as e:
            logger.warning(f"Client {bundle.client_id}: PG::verify ERROR — {e}")
            return False, f"PG::verify ERROR — {e}"
    else:
        return False, "Non-real proof rejected: fallback proofs are disabled"

    # 1. EMA norm bound check
    if ema_bound is not None and ema_bound.bound is not None:
        norm_float = float(np.sqrt(norm_sq_quantized)) / SCALE
        if not ema_bound.check(norm_float):
            msg = f"REJECTED — norm={norm_float:.4f} > EMA bound={ema_bound.bound:.4f}"
            logger.info(f"Client {bundle.client_id}: {msg}")
            return False, msg

    # 2. Directional check (Blocks Sign-Flips and Obtuse angles)
    if dir_fp_quantized < -1e-6:
        msg = f"REJECTED — Directional bound violation: inner_product < 0 ({dir_fp_quantized})"
        logger.info(f"Client {bundle.client_id}: {msg}")
        return False, msg

    return True, "Valid"

def verify_proof_batch(bundles: List[GradientProofBundle]) -> Tuple[bool, str]:
    """Verify a batch of independent ZK proofs natively without folding.
    
    Proof-Carrying Data (PCD) for combining independent IVC proofs is not natively 
    supported by upstream Sonobe for ProtoGalaxy. We perform rigorous O(N) validation.
    
    Args:
        bundles: List of client proofs to verify
        
    Returns:
        (bool, reason): True if all proven mathematically valid, False otherwise
    """
    if not _ZKP_AVAILABLE:
        raise RuntimeError("ZKP bridge unavailable. Fallback verification is disabled.")

    if not bundles:
        return False, "No proofs to verify"

    try:
        for i, bundle in enumerate(bundles):
            ok, msg = verify_gradient_proof(bundle, expected_model_fp=bundle.model_fp)
            if not ok:
                return False, f"Proof {i} failed: {msg}"
        
        return True, "All component proofs cleanly verified natively"
    except Exception as e:
        logger.error(f"Batch verification failed: {e}")
        return False, str(e)
